version: "3.9"
services:

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "alembic", "upgrade", "head"]
