version: "3.9"
services:

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network

  web:
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "./wait-for-it.sh postgres:5432 -- alembic upgrade head && python /code/add_data_to_db.py"

    networks:
      - blog-network

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6380:6379"
    restart: always
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
