version: "3.9"
services:

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env.local
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
